### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#100]
We are using a couple of fonts for the plugin but we aren't loading them anywhere, like Lato. So if user's computer doesn't have Lato, it loads Times New Roman which looks bad, so we should the fonts.

@selu91

**Comment by selu91** [comment]
@ineagu what do you think ?

**Comment by ineagu** [comment]
can you look into it ? Why we aren't loading Lato ? where are we using it ? When we stopped loading it ? :D  I would love a more detailed overview, maybe with some screens so I can decide quicker :D

**Comment by HardeepAsrani** [comment]
@selu91 I really can't answer these because I have no idea why the developer (whoever it was) decided to not load the fonts.

I presume because he thought all computer would have it, like my Windows has it preinstalled.

**Comment by selu91** [comment]
ok, im closing this until i have more details
