### ISSUE TITLE
bug  rating

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#102]
can you check this: 
https://wordpress.org/support/topic/bug-strange-agregate-rating-instead-of-normal-one?replies=6

**Comment by contactashish13** [comment]
@selul I can't see the "comment influence" setting anywhere. Can you help?

**Comment by selul** [comment]
http://prntscr.com/bmz84p

**Comment by contactashish13** [comment]
@selul I'm not sure what the behavior is expected. Can you please advise what is required?

**Comment by selul** [comment]
@HardeepAsrani can you please explain ?

**Comment by HardeepAsrani** [comment]
@contactashish13 The user turned on the comment ratings when he created the post, and now he has turned off the comment ratings and deleted the ratings but the review is still the same.

**Comment by selul** [comment]
@contactashish13 hardeep is talking about richsnippet, when we turn on the comments influence we show the agregate rating tag

**Comment by selul** [comment]
@contactashish13 any news here ?

**Comment by selul** [comment]
i have released the fix
