### ISSUE TITLE
Remove Buy now / Read review buttons if text values are empty from Top/Latest Product Widgets

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/wp-product-review#108]
See here: https://github.com/Codeinwp/wp-product-review/blob/27f04684f51ada683dd79faa0d21851fc2a6bb76/inc/widget-layouts/style%201.php#L57-L58

There's no check to see if `$instance['cwp_tp_buynow']` actually contains anything. See attached screenshot for issue.

![screen shot 2016-08-05 at 15 10 37](https://cloud.githubusercontent.com/assets/7841556/17436303/cb982970-5b1e-11e6-835e-d1e80f6dd3cd.png)

**Comment by selul** [comment]
@contactashish13 can you check this for both layouts and both widgets ?

**Comment by contactashish13** [comment]
done
