### ISSUE TITLE
integrate a/b testing for upsell texts

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#110]
@contactashish13 i would like to build a separate script that will do some ab testing on upsell texts. 

The texts will be simple html strings and will be grouped in sections. 

The configuration array will look like this 
```

$config = array (
    "icons" => array("html string 1", "html string 2", "html string 2")
    "preloader" => array("html string 1", "html string 2", "html string 2") 
) 
```

The main logic will be built in a separate script which will use a filter to alter the config variable. The scope is that the general script to be used across multiple plugins but the configuration to be defined in each plugin. The filter will contain also the product slug. For Wp product review we will define it as a constant in wp-product-review.php, called wppr. 

When i would like to echo the html strings i will use another filter $product_slug."_".$section."_upsell_text"

For instance if i would like to output the upsell html for the icons section i will use apply_filters ( "wppr_icons_upsell_text" and will get a random string between those 3 defined for the icons sections. 

Let me know if you have any questions

**Comment by selul** [comment]
@contactashish13 please take care of escaping the html and make it translation ready

**Comment by contactashish13** [comment]
@selul do you also want to collect stats against each text that is shown i.e. whether it was clicked or not?

**Comment by selul** [comment]
no, just echo the html. The html will include tracking links, so no need for this.

**Comment by selul** [comment]
@contactashish13 i have added some comments there
