### ISSUE TITLE
Notices on plugin activation

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-product-review#111]
http://prntscr.com/c7ajsr

 Notice: Undefined index: cwppos_show_poweredby in C:\wamp64\www\wordpress\wp-content\plugins\wp-product-review\inc\wppr-main.php on line 343

Notice: Undefined index: cwppos_show_poweredby in C:\wamp64\www\wordpress\wp-content\plugins\wp-product-review\inc\wppr-main.php on line 356
@selul

**Comment by selul** [comment]
thanks @rodica-andronache  :D
