### ISSUE TITLE
add filters for nofollow links

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#116]
@contactashish13 here https://github.com/Codeinwp/wp-product-review/blob/production/inc/widget-layouts/style%201.php#L58-L61 

We have 2 nofollow links, i would like to offer the users the chance to alter the html code of the links using filters. Please echo the html code for that, by applying a filter which will receive the post id, review link and text for buy btn or read review. will be 2 filters for each of the btns, **wppr_widget_style1_buybtn_link** **wppr_widget_style1_readreview_link**

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/wp-product-review/pull/117
