### ISSUE TITLE
keep upsell choice

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#120]
@contactashish13 i would like to edit the upsell links class, the one you developed, to save the upsell link per each choice and no longer choose another per each page view. 

Use case : 

1) User goes to the page where is the upsell link present and he will use one text variation from the config list
2) user come back, he will see the same variation

Please save the variation per each product version, i.e when he will update the product, the text will be randomly choose again but save it until the next product update. 

How can you achieve this is send to the `TIABTesting `constructor the wppr lite version, and save the option in the db based on this slug. for instance the upsell link for preloader will be saved with `wppr_3_3_0_preloader_upsell `

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/wp-product-review/pull/122

**Comment by contactashish13** [comment]
@selul done. I wasn't sure if it mattered as I couldn't think of a scenario where it would be a problem.
