### ISSUE TITLE
Enable / disable rich snippets

### ISSUE THREAD

**Issue by stayallive** [Codeinwp/wp-product-review#131]
It would be very usefull to be able to disable the rich snippets since we would like to have a shortcode in our content that displays the review and also the default display on the bottom causing Google to see two reviews and thus ignoring both on the search results page :(

**Comment by ineagu** [comment]
I agree with this @selul  I just haven't done it cause it was a mess some time ago. Ideally in pro version we can also give more granular control for people so they can edit the details , something like : https://wordpress.org/plugins/all-in-one-schemaorg-rich-snippets/screenshots/ .

**Comment by jphorn** [comment]
I really like the granular control which [WP Rich Snippets](https://wprichsnippets.com/doc/shortcodes/) offers in their shortcode. Their extensibility *and* the option in the shortcode to disable the microdata output would be perfect imho.

**Comment by selul** [comment]
Thanks for feedback, i will prepare the specs for the next releases and we will include it.

**Comment by HardeepAsrani** [comment]
Any update here? @selul

**Comment by jphorn** [comment]
Any update? See also #151.

**Comment by ineagu** [comment]
cc @selul @preda-bogdan
