### ISSUE TITLE
German Translation issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-product-review#133]
@selul @rodica-andronache Problema este ca nu se traduc titlurile de Pros so Cons. Chiar daca a modificat fisierele .po si .mo nu se schimba. Aici am testat si eu si problema chiar exista, nu se traduc.

![](https://d33v4339jhl8k0.cloudfront.net/inline/12894/4a7529784177758d6da41001d1cc7f383dabaaa6/825412c2b40377824faa8503519933edd052c33d/Screenshot_1.png)

**Comment by mileamadalin** [comment]
@rodica-andronache aici mai facem ceva? :D

**Comment by selul** [comment]
@mileamadalin nu momentan, or sa fie niste modificari in plugin si o sa schimbe o parte din ele. o sa ne ocupam dupa de traduceri.
