### ISSUE TITLE
 feature review bar (slider) is not working

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-product-review#135]
@selul the customer ticket: https://secure.helpscout.net/conversation/168809086/73355/?folderId=212390 

It doesn' allow user tap&amp; drag but hit on the somewhere, and cannot drag from the point you tap,,,,

**Comment by selul** [comment]
[wppr-mobile-fix.zip](https://github.com/Codeinwp/wp-product-review/files/589866/wppr-mobile-fix.zip)

here you go, you can send the user this plugin and the slider should work accordingly.

**Comment by selul** [comment]
@mileamadalin please close it once done

**Comment by mileamadalin** [comment]
@selul Thanks
