### ISSUE TITLE
WPPR - Best size for images

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-product-review#136]
@selul We should add a small text in setting to add the best size for the thumbnail image. Under or above this text: "*If no image is provided, featured image is used" In Product Review Extra Settings. What do you think?

**Comment by UVLabs** [comment]
+1

**Comment by HardeepAsrani** [comment]
+1

**Comment by selul** [comment]
@rohittm can you have  a look at this ? you can ask @contactashish13 for assistance if you need any help. Also, we can provide a link to the doc where we show them how they can change the image size.

**Comment by rohittm** [comment]
@selul PR #224

**Comment by selul** [comment]
@rohittm there are too many files changed, it seems you changed a lot regarding the indentation. Submit a PR with only the files needed for the changes.

**Comment by rohittm** [comment]
Alright. i guess there was issue regarding grunt. I ran phpcbf. Anyways, I'll figure it out and make a new PR.
 You can close this one

**Comment by selul** [comment]
@rohittm you can ask @contactashish13 for help.

**Comment by rohittm** [comment]
@selul PR #227

**Comment by selul** [comment]
Well done.
