### ISSUE TITLE
amp support

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-product-review#143]
https://wordpress.org/support/topic/amp-support-11/

cc @selul

**Comment by HardeepAsrani** [comment]
So to add the plugin to AMP the person has to use the shortcode extension. If you add the plugin to the post content using shortcode it works. I noticed that you can't use Google AMP if you're using WP Product Review because of some errors with our code. I've fixed it and will send a pull.

**Comment by HardeepAsrani** [comment]
Apart from that, if someone is using AMP for WP plugin then we can use `ampforwp_after_post_content` and `ampforwp_before_post_content` to add to the template.
