### ISSUE TITLE
Filtering option to easily find review posts

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/wp-product-review#150]
It's sometimes hard finding review posts amongst other posts on a website, could we maybe implement a filter similar to what YoastSEO does to easily filter review posts?

http://prntscr.com/f7siux

**Comment by selul** [comment]
@contactashish13 now that we have the comments rating that affects the review model query in place, we can now try to work on this. 

 * The select will be on all post types admin listing pages
 * It will have the next options ( Show only reviews  :  no | yes | over 3, over 5 rating, over 7 rating. When the rating flag is set in the url, we should add a column where we display the rating also.

**Comment by contactashish13** [comment]
@selul 

> The select will be on all post types admin listing pages

if users use many CPTs, it might become irritating for them. maybe this should be given as an option to the user?
OR
we can check if the current post type being displayed has even one review, if yes then show this.

**Comment by ineagu** [comment]
As a user I would love to have just a select to see only review posts, sorting by rating seems useless in the context proposed by @UVLabs 

Another option is to show the text - Review after the name of the post, for e.g check how Gutenberg/Elementor shows posts edited with them in the posts list.

**Comment by HardeepAsrani** [comment]
Just having a column in the Post screen, like Comments option, will be good to: https://s.nimbus.everhelper.me/share/1294434/t6izrpd5r8h4hgfwi6yl

Something people are used to already.

**Comment by selul** [comment]
@contactashish13 yes, let's keep things simple. For the moment add them just to posts/pages, use a filter to filter them in order for developers to add more post_types.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/226
