### ISSUE TITLE
Use JSON-LD for Rich Snippets

### ISSUE THREAD

**Issue by jphorn** [Codeinwp/wp-product-review#151]
Please note Google now supports and **[recommends](https://developers.google.com/search/docs/guides/intro-structured-data)** JSON-LD implementation for all rich snippets.

**Comment by selul** [comment]
@preda-bogdan let's remove the current rich snippets from the new version and the support for JSON-LD. I think this will also make the code much easier to follow and we can add also a setting in the global settings area for enable/disable this

 - [ ] Add JSON-LD support
 - [ ] Add setting for enable/disable this.

**Comment by preda-bogdan** [comment]
@selul Done please check if implementation is as intended.

**Comment by selul** [comment]
@preda-bogdan can you use the same textdomain wp-product-review instead of cwppost, even if that one was before.
