### ISSUE TITLE
[Feature Request] Top Reviews Widget Time Span

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/wp-product-review#152]
"Limit the date of the reviews to 1/year 1/month or something.. because you will have always the same reviews in the widget.... if you have one review with 100/100 point never disappear no matters how old is the product."

**Comment by Naismith75** [comment]
Please add this feature, the widget is not useful in the actual way.
Other reviews plugins have this, i don't want to change.

**Comment by Naismith75** [comment]
Please add this feature, is not complex and very useful.

**Comment by Naismith75** [comment]
Please, support your product... don't leave your users alone.
