### ISSUE TITLE
Widgets not working with page builders

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#154]
Ref: https://wordpress.org/support/topic/change-widget-button-text-inside-plugin-code/#post-9269625

Widgets aren't working because they require some JS which we only load on Widget page, not Post editor.

Should we load it on editor as well? I can send a pull. @selul

**Comment by ineagu** [comment]
I think @preda-bogdan can look at this, we can load in the editor as well, but only for builders I suppose.

**Comment by preda-bogdan** [comment]
@HardeepAsrani 

Solved in the new release.

cc: @ineagu
