### ISSUE TITLE
templating system

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#159]
@preda-bogdan for all layouts used in the free and pro version you need to add the option to be overwritten in the theme folder.

basically if a file with the same name exists in the wppr folder of the theme, we use that instead of the one from plugin.

**Comment by preda-bogdan** [comment]
@selul all templates are now checked in a folder called `wppr`

The templates that can be override are:
default.php -- the default full post product view
rating.php -- the minimalist rating template from PRO
score.php -- the score template from PRO
table.php -- The table template from PRO ('The Comparison table Addon PRO')
listing.php -- The listing template from PRO ('The Listings Addon PRO')
