### ISSUE TITLE
load assets when needed

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#166]
Currently the frontend assets loading is not the best one, i would like to optimize them a bit and separate the files accordingly. 

1) js files for pie chart loading.
2) js file for rating loading 
3) css file for widget  style 1
4) css file for widget default
5) css for pie chart only.
6) css for full review box 
7 ) css for comparison table.
8) css for listing table

the inline css and  js strings should be pe added only to the files which needed, ie attached to the relevant handles. 

The loading should be done accordingly: 

1) when is the full review is displayed ( either added to the post_content, shortcode, or using that legacy function **cwppos_review**, depending on the visual parameter, we should load 
for visual full - 1,2,5,6
for visual yes - 1,5
for visual no - nothing. 
2) When using the widgets 
   - if style 1, load 1,3
    - if default, load 1,4
3) when using listing table, load 8
4) when using comparision load 7

**Comment by selul** [comment]
@contactashish13 can you take care of this ?

**Comment by contactashish13** [comment]
@selul PRs: https://github.com/Codeinwp/wp-product-review-pro/pull/57 and https://github.com/Codeinwp/wp-product-review/pull/192

I could not find this
> using that legacy function cwppos_review

**Comment by selul** [comment]
you can find it in the legacy.php in lite version.

**Comment by contactashish13** [comment]
@selul done.
