### ISSUE TITLE
Manually Place content option

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#181]
Lite version has Manually Place option for the review box while it doesn't support the shortcode, but has some weird sentence below that doesn't make much sense: https://s.nimbus.everhelper.me/share/1114481/io45zwsmzwq62fzuosrh

@selul

**Comment by mileamadalin** [comment]
@selul We have two clients who reported us this issue. I have checked as well on my local machine and have the same problem. The shortcode doesn;t work for the Manual Place (Lite and Pro version same issue).
