### ISSUE TITLE
add widget review selector. 

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#186]
@contactashish13 we should for the latest and top widgets available a selector for selecting the post_type to choose when querying the reviews.

The review query class is allowing post_type filter, you can check that, for the moment we use post and page post types when querying. 

I would like to add one selector to each widget, where users can select from the available post_types or all of them when filtering the reviews. 

Also, when selecting a specific post, we would need also to show the 2nd selector, for categories, with the proper taxonomies for that post_type. We will show only the hierarchical taxonomies, for instance for page post_type, we won't have a selector for categories. 

When finishing this, i would like for you to test if we had previously a widget targeting a specific category, after upgrade to this version, to show the same results.

Let me know if you have any questions.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/190

**Comment by selul** [comment]
@contactashish13 i get this https://drive.google.com/file/d/0B8cbkQkB9YbnRnNpMmFpd0NlUVU/view when using the review selector, i think the content get refreshed and the binds get removed

**Comment by contactashish13** [comment]
@selul strangely, my WP on both 4.7.2 and 4.8.2 has no support for live widget - they still add widgets in the old way so I could not test these. Have tested on sandbox and fixed.
