### ISSUE TITLE
top reviews widget time span

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#187]
@contactashish13 for top review widget, i would like to add a timespan selector having this value. 

latest week, latest month, last 3 months, last half year, last year.

This selector will filter the reviews who were published ( post_date ) only in the desired time interval. The best way is to add a new component in the find method for review query class, which will accept the date interval. 

Based on the date value, we will build the conditions, same fashion as we do for rating.

**Comment by contactashish13** [comment]
@selul maybe we can use something like https://jqueryui.com/slider/#range and let the user toggle weeks? This might make it more flexible. Let me know

**Comment by selul** [comment]
ok, might work, let's add between 1-99

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/191

I've made the selector between 52 weeks and 0 and defaulted it to 1 and 0. These values can be changed if they dont work.

**Comment by selul** [comment]
@contactashish13 i would like the default to be zero, and in this case to ignore the time interval, to work like now.

if this is not the actual behaviour we should make it.

**Comment by contactashish13** [comment]
@selul done.

**Comment by contactashish13** [comment]
@selul i don't see any comments on the commit or the PR

**Comment by selul** [comment]
ah, i forgot to submit the review :D

**Comment by selul** [comment]
@contactashish13 can you fix the conflicts in this pr ? https://github.com/Codeinwp/wp-product-review/pull/191

**Comment by contactashish13** [comment]
@selul done
