### ISSUE TITLE
tags and categories are considered the same in the review query.

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#189]
@contactashish13 when querying a set of reviews, based on the category name, we don't consider the taxonomy type. let me give you an example.

We have in the system two categories  with slug name `vegetables` and a tag name with the same slug `fruit`

we have a widget which queries reviews from vegetables category. 

we have a review which has the tag fruit but is not in the vegetables category. 

the widget displays also this review because when quering we don't limit the category name to the taxonomy. 

i hope i was clear enough :D

**Comment by selul** [comment]
it might get solved when  https://github.com/Codeinwp/wp-product-review/issues/186 is finished

**Comment by contactashish13** [comment]
@selul I'm not sure I understand the below. I dont think one can have two categories with the same name. Can you please clarify? 

> We have in the system two categories with slug name vegetables and a tag name with the same slug fruit

**Comment by selul** [comment]
not categories, i'm talking about tag and category, one tag having the same name as a category.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/196
