### ISSUE TITLE
issue with latest dev version

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#200]
@contactashish13 using the development version of wppr, when building a new review , if i get to see it from the frontend i get this: 
![image](https://user-images.githubusercontent.com/3330746/31936505-6ab37074-b8ba-11e7-8c13-f890585e0288.png)

**Comment by contactashish13** [comment]
@selul I'm not sure the sections and fields should be defined when its a front-end call. Anyways, I've fixed it so that disqus and jetpack are not checked if the page is being called from the front end.

PR: https://github.com/Codeinwp/wp-product-review/pull/202
