### ISSUE TITLE
Include/Exclude categories based on social media network for Revive Old Posts plugin

### ISSUE THREAD

**Issue by harshv251** [Codeinwp/wp-product-review#207]
One user has suggested a feature request for Revive Old Posts plugin, Include/Exclude categories based on social media network. Please check this thread for more details
https://wordpress.org/support/topic/include-exclude-categories-based-on-network/#post-9654176

**Comment by selul** [comment]
@harshv251 i think you have added in the wrong repo :D

**Comment by HardeepAsrani** [comment]
That's my mistake. I copied wrong link from my browser. :D
