### ISSUE TITLE
improve comments rating 

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#210]
i would like to improve how the ratings are stored and how they affect the review. 

Right now the comments rating is affecting only the global rating value, the individual options are still still using the editors rating. Some users get confused  because the comments ratings are no reflected to the review options too. 

Also another issue is that the top widgets rating is sorting the rating correctly when the user influence is on. 

In order to fix all those issue i suggest the following changes: 

1) Alter the `setup_options`, check if the comment influence is turned on, and  use `get_comment_options` to alter the options based on the user reviews. Make sure you alter the options rating according to the influence setting.
2) In order to solve the top rating widgets issue, we will need to store the comments average rating rating, returned by `get_comments_rating` in a post meta and update it each time someone adds a new comments review. In this way we will have the review rating and comments rating separated. The next thing will be to edit the query model class to order the results based on a **SQL** math operation which will use influece rating, comments rating and review rating, similar with this but at sql level: https://github.com/Codeinwp/wp-product-review/blob/master/includes/admin/models/class-wppr-review-model.php#L681

Let me know if you have things clear.

**Comment by contactashish13** [comment]
@selul can you check if the calculation is correct for part 1 of the issue: https://github.com/Codeinwp/wp-product-review/pull/214 ?

**Comment by selul** [comment]
@contactashish13 yes, it seems ok, i dont understand the purpose of $prefix variable, could you please share you thoughts ? 

also, one small recommendation would be to use in your code a return early approach, which makes you code easier to read and follow. 

For instance those lines:

```

		$comment_influence = intval( $this->wppr_get_option( 'cwppos_infl_userreview' ) );
		if ( $comment_influence > 0 ) {
			$comments = $this->get_comments_options( 'id' );
			if ( $comments ) {
				$combined = array();
				foreach ( $comments as $comment ) {
					....
				}
			}
		}
                

``` 

Could be turned into: 

```
                if ( $comment_influence === 0 ) {
		   return;
		}
		$comments = $this->get_comments_options( 'id' );
		if ( empty( $comments ) ) {
		   return;
		}
		$combined = array();
		foreach ( $comments as $comment ) {
					....
		}

``` 
Which for me seems easier to read.
Makes sense ?

**Comment by contactashish13** [comment]
@selul will take care of these.

for problem 2, instead of calculating through SQL wouldn't it be better to save the user-influence calculated score as a meta value and then use that value when ordering the results? if user influence is not on, then we use the rating meta otherwise the calculated meta.

**Comment by selul** [comment]
@contactashish13 i don't understand your approach, can you please tell me a simple use case ?

**Comment by contactashish13** [comment]
@selul right now the problem is that the top products widget does not take into account user influence. for it to do that, either we have to calculate the final rating in PHP or in SQL and then order by that. Your suggested approach is to calculate the final rating in SQL. It would be more efficient to calculate this in PHP, then save it as a meta and then use this to order.

**Comment by selul** [comment]
@contactashish13 i dont have very clear how you want to do it.  If we will do the calculation in PHP, we will need to load all the reviews from DB, which is not ok because some users will have thousands of reviews.

We can have a call if you want to clear all the things here.

**Comment by rohittm** [comment]
Just a question, I want to know if we keep appending  the ratings in an user API, and then calculate using the objects parameters in a main object (let’s call it main) as soon as the ratings are added? how woll it go?

**Comment by selul** [comment]
oh @rohittm you're losing me ... can you be more specific ?

**Comment by rohittm** [comment]
Let's take an example here:

{
    [ "Main": {
                     "option1": a,
                     "option2": b,
                     "option3": c
                     }
     ],
     [ "User_Ratings": {
                     "option1": a,
                     "option2": b,
                     "option3": c
                     },
                     {
                     "option1": a,
                     "option2": b,
                     "option3": c
                     },
                     {
                     "option1": a,
                     "option2": b,
                     "option3": c
                     }]
}

is a JSON from an API. When there's a new entry, It will be appended to User_Ratings object, and alongside, the Main objects Ratings (influenced one) will be calculated from the algorithms we are using.

P.S. I'm new to all these things, just asking if these things are possible?

**Comment by selul** [comment]
yes, abstracting things, you are right, but there is no json api for each comments/user.

**Comment by contactashish13** [comment]
@selul have rectified the issue with top widgets sorting too. please check.

**Comment by selul** [comment]
@contactashish13 should be fine now, good job
