### ISSUE TITLE
comments rating display

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-product-review#211]
@selul here is how comments ratings looks like on islemag -> https://www.dropbox.com/s/70589ukej05uth8/Screenshot%202017-11-09%2010.23.19.png?dl=0

https://www.wabeo.net/bu-saint-jerome/

**Comment by selul** [comment]
@bogdanpopa90 can you have a look

**Comment by bogdanpopa90** [comment]
Related to https://github.com/Codeinwp/islemag/issues/243
