### ISSUE TITLE
improve amp support 

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#218]
@rohittm looking at [this ](https://secure.helpscout.net/conversation/464125501/147480/?folderId=212392 ) ticket, it seems we have an issue with amp support.

@rohittm i would like for you to  install wppr and that amp plugin, and improve layout of the review area. 

After you finish this, you can ask @contactashish13 to review the code.

**Comment by rohittm** [comment]
Hey @selul, can you please update the ticket URL here?

**Comment by selul** [comment]
yep, here it is: https://secure.helpscout.net/conversation/470811491/148356/?folderId=212390

**Comment by rohittm** [comment]
@selul PR #233

**Comment by selul** [comment]
@rohittm this is not really the happiest way of solving this, we use OOP for plugin code, you have added your code using a more procedural approach. 

You need to leverage the use of the current classes and methods to achieve the AMP support. 

You can ask @contactashish13 to review your code and give you more details about the best way to solve this. 

This is a good start, however we still have a bit more work to do to have it production ready.

**Comment by rohittm** [comment]
@selul PR #233
