### ISSUE TITLE
Rating slide goes beyond 0 when scrolled back.

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/wp-product-review#230]
Difficult to explain. Following steps can produce it:

1. Enable reviews for comments.
2. Go to the comments section on any post in front-end.
3. Now, click on the first review slider starting point dot and drag it backside. 
4. You will be able to drag it backside which also makes the review range bar a bit longer than the rest of others. 

Screenshot to explain better - http://prntscr.com/hmxkdy. 

I checked this with the Oblique theme. 

@selul

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/232
