### ISSUE TITLE
Button Icon color not changing

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/wp-product-review#236]
@selul the button text color is changing via the setting but there's no setting to change the button icon color, it stays blue: https://prnt.sc/i0iogv and on hover it goes white, but there's no way to change the button icon color on hover as well

**Comment by selul** [comment]
@contactashish13 can you check this out.

**Comment by contactashish13** [comment]
@UVLabs can you please specify what other options are required besides the ones that exist?

![image](https://user-images.githubusercontent.com/12953439/37136890-7bdddc30-22c9-11e8-91e1-7f9c0818e93b.png)

**Comment by contactashish13** [comment]
@UVLabs could you please respond?

**Comment by UVLabs** [comment]
@contactashish13 ok let me get back to you here in the next few hours

**Comment by UVLabs** [comment]
@contactashish13 the icon color of the button: https://prnt.sc/iv251v

**Comment by contactashish13** [comment]
@selul that image is a blue icon. do we need to give multiple options for this image?

**Comment by UVLabs** [comment]
@contactashish13 ideally it should inherit the "text color" set in the plugin and not be a static image

**Comment by contactashish13** [comment]
@UVLabs thanks.

@selul PR: https://github.com/Codeinwp/wp-product-review/pull/269
