### ISSUE TITLE
RTL Compatibility

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#238]
Found few issues with RTL compatibility: https://s.nimbus.everhelper.me/share/1447592/ocln574nav3pcict1pwv

- The button isn't working properly.
- The rating system and knob should be opposite as people who write in RTL also perceive time and value to go from Right to Left.

For example, if you have a progress bar, it goes from Right to Left. It changes how we perceive time and values change in RTL and LTR writing styles.

We usually have Before in left After in right, they have the opposite. Just a physiological fun fact. :D

**Comment by contactashish13** [comment]
@HardeepAsrani can you check with PR https://github.com/Codeinwp/wp-product-review/pull/293?

I cant do much about the stars in style 1 :)

**Comment by rodica-andronache** [comment]
@contactashish13 there are still small things that don't look good 👍 
maybe add some padding to between the icon and the text in the button. The icon should be in the right side of the text in rtl mode
![hello world wordpress](https://user-images.githubusercontent.com/3266155/41534347-ec8a2cf8-7306-11e8-94c0-eecd51735b62.png)
![hello world wordpress 1](https://user-images.githubusercontent.com/3266155/41534477-5cc57ef0-7307-11e8-8a31-7f64b5166750.png)
the stars should be filled in the other direction in all 3 templates

**Comment by contactashish13** [comment]
@rodica-andronache I don't see any problem with pros and cons. They seem to be identical in RTL and LTR. Can you please compare and then let me know what changes you foresee?

As for the stars, I think we will have to change our approach to using full and half stars instead of fractional stars. Basically, any quantity can be converted to x or x.5 where x is a whole number. Then we can easily support RTL. With the current approach, I've tried all combinations and it does not seem possible.

Also, the stars in the widget use a completely different methodology. I think these should also be converted to using font awesome like in the main ratings. 

Let me know what you think.

**Comment by rodica-andronache** [comment]
@contactashish13 for the pros and cons, if you check that template from the screenshot, you will see that in the rtl mode there is an extra padding, as in the screenshot :)
For the stars, sure, we can change the way the filling is done.
And don't forget about the buttons, which doesn't work well in rtl 👍  and the cart icon in the button, to be on the other side in the button.
Let me know if there's something that's not clear :)

**Comment by contactashish13** [comment]
@rodica-andronache I'm not sure I understand what you mean by this padding. They seem to fine to me. Please highlight the portions in both RTL and LTR that you find have unnecessary padding.

![image](https://user-images.githubusercontent.com/12953439/41648025-703cec22-7495-11e8-85bf-37508cd965ef.png)

![image](https://user-images.githubusercontent.com/12953439/41648135-bab064d2-7495-11e8-8d49-fb3a1b628912.png)

**Comment by rodica-andronache** [comment]
@contactashish13 https://prnt.sc/jx3rol

**Comment by contactashish13** [comment]
@rodica-andronache that helped! Have addressed all issues.

**Comment by rodica-andronache** [comment]
@contactashish13 I think there are still issues if you want to check. I tried to explain everything I saw and I think needs to be done. In theory, it should be like the LTR but in the mirror 👍 
first template: https://prnt.sc/jxn8i1
second template: https://prnt.sc/jxna9s
third template: https://prnt.sc/jxnbcj

**Comment by contactashish13** [comment]
@rodica-andronache have fixed the issues you pointed out plus a few more that I discovered while testing. 

1st template
- Have interchanged the position of the rating and the image in RTL.
- There is a border on the RHS of the image. I have retained it but don't think it should be there. The border is obvious in RTL.

2nd template
- I think the text should be in the center and the rating of the option should be on the left in RTL.
- In mobile view, the UI breaks. Have fixed it. 

3rd template:
- I think that the stars should be on the LHS not RHS in RTL.
- The spacing between the option and the rating is something I can't do much about. Might need a CSS expert for this.
- Have interchanged the position of the rating and the image in RTL.

**Comment by contactashish13** [comment]
@rodica-andronache I've commented on what you have pointed out in templates 2 and 3. There are points I disagree with if you consider RTL to be a mirror image of LTR. Can you please review my points in detail?

**Comment by rodica-andronache** [comment]
@contactashish13 I am testing using https://wordpress.org/plugins/rtl-tester/, is it possible that this could be the cause? How are you testing? I'm not sure how to actually enable rtl

**Comment by contactashish13** [comment]
@rodica-andronache maybe that could be the cause as I'm not using that. I'm changing the site language to an RTL language and testing.

![image](https://user-images.githubusercontent.com/12953439/42087028-908a8510-7bb2-11e8-8abd-23edec5ae6e4.png)

**Comment by rodica-andronache** [comment]
@contactashish13 thanks :) I tried with the same language like you did, with  #293 with Codeinwp/wp-product-review-pro#95 with Twentysixteen
But I still see of the issues I mentioned and that for me really make sense:
template 1: https://prnt.sc/k2foy2
template 2: https://prnt.sc/k2fpkn (Here you previously said: "I think the text should be in the center and the rating of the option should be on the left in RTL.". Could you maybe explain why do you think so? I mean, why in LTR the text should be at the end of the bar, but in RTL it should be in the center? )
template 3: https://prnt.sc/k2fq3g (Here you said: "The spacing between the option and the rating is something I can't do much about. Might need a CSS expert for this." Wouldn't it just need to add left right on RTL for .wppr-template-2 .wppr-review-option-rating ? )

**Comment by rodica-andronache** [comment]
@contactashish13 thanks :D  there were still some problems, with the button, but it's ok, I've fixed them. I see you don't like css that much :D And for the build, you had to run grunt local to fix them 👍
