### ISSUE TITLE
Top rated products by tag or custom taxonomy

### ISSUE THREAD

**Issue by bwalklet** [Codeinwp/wp-product-review#239]
The top products widget is great, but I think it would be perfect if we could display top rated products by tag or custom taxonomy, not just category. Additionally, being able to only display products published in a certain year would be awesome (not just a time range of last 0-52 weeks).

**Comment by selul** [comment]
Hey @bwalklet, 

Thanks for your feedback. 

Regarding your first suggestion, this is already possible, you just need to have reviews in those taxonomies and they should show in that widget. If is not, please let us know and we will investigate. 

As for the 2nd idea, sounds like a good feature to add in the future. We will surely consider it.

**Comment by bwalklet** [comment]
When did this become possible (which version)? I am only seeing the option to select a category.

https://www.dropbox.com/s/fcsy4g6kdfz47cg/Screenshot%202018-03-05%2012.34.17.png?dl=0

**Comment by selul** [comment]
@bwalklet yes, you're right, I rushed with this thing. It seems that filter by tags is still work in progress.

**Comment by alidixon03** [comment]
+1 for filtering by tags. That would be great as I have a ton of reviews currently in a category that is not called "reviews", changing this will mess up all my SEO.
