### ISSUE TITLE
CPT or not-CPT

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-product-review#243]
@selul I can see a reason why it would be useful for some people to have a separate CPT for reviews, I can imagine that having a setting : Enable CPT shouldn't be hard to implement right?

When enabled users will have a reviews cpt similar to post, just that the review part will be automatically enabled.

Existing filters for gettings reviews, can be updated to check this cpt as well along with posts.

**Comment by selul** [comment]
@ineagu How we/users will leverage this feature ?

**Comment by ineagu** [comment]
it might be indeed an edge case but here are some examples 👍 

1. User don't wanna display reviews on their blog listing
2. users want a review archive page with specific fields/design
3. I suppose this can be more naturally integrated with other plugins

saw some users requests as well, if we keep them coming we can add more info here.

**Comment by selul** [comment]
@contactashish13 let's tackle this. 

The intent is to add a custom post type, same proprieties as the post post_type where they can add reviews. You will introduce a new taxonomy also, called category reviews. 

This will be enabled if they will check a setting in the global settings area, called enable review post type, by default false.

Requirements: 

 - add a checkbox called Enable review post type, by default unchecked.
-  when enabled, this will enable the `wppr_review` and `wppr_category` taxonomy. 
-  on the admin edit screen for this post type, they will have a slightly different edit screen. The checkbox for enabling the review will be **ON** here by default and the review name field will be removed. Instead of the review name, we will use the review post title.  Make sure you will adapt the review model for this change also. 
- make the reviews made with the old system works as before and they will work the same in the future too.
- make the appropriate unit tests for this change

**Comment by contactashish13** [comment]
@selul if users already have some reviews and they then check this CPT, they will have reviews in post as well as wpp_review. Maybe if they check this, we should display a message that their existing reviews will be migrated to this? 

Also, let's assume some users are using this new version where they have checked this CPT. Should they now be allowed to uncheck this box? If they do, then again their reviews will be in posts and not in the CPT.

One way around this is to not allow users to uncheck once they have checked this.

**Comment by selul** [comment]
Nope, this will be more simple than this. It will be no change to the older reviews, when enable the cpt, they will have only different defaults to the editor, nothing else.

**Comment by contactashish13** [comment]
@selul so when existing users who already have reviews enable this, they will have reviews in posts as well as in this post type?

**Comment by selul** [comment]
yep, this post_type will offer just a way of keeping reviews in one place, without any change for the existing ones.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/256

I can't seem to get the Add Review and Review Categories menu items when attaching them to the main WPPR menu. They are displayed if I choose to show them in their own menu but not as a subset of the main WPPR menu.

**Comment by selul** [comment]
@contactashish13 i dont want to be added under WPPR, we can have as regular menus, as we add any other cpt.

**Comment by contactashish13** [comment]
@selul as a matter of fact, we include CPTs under the menu item of the plugin e.g. pirate forms. Anyways, I've made these independent here.

**Comment by selul** [comment]
@contactashish13 nicely worked. 

@rohittm can you test this feature and let me know if you see any issues.
Some use cases that I would like to test, ofc I would like for you to think of more scenarios 

1) Create a review using the new review post type, check if the review single page is looking ok, without any errors.
2) Render a wppr review shortcode with a post type review id, make sure the review box is showing fine.  


let me know how is going.

**Comment by rohittm** [comment]
@selul The two test cases you asked me to test worked fine with me. One thing I noticed, that the product title is not being showed when used as shortcode. Here's the example:

Here is the CPT review:

![screen shot 2018-03-13 at 00 44 41](https://user-images.githubusercontent.com/3204558/37304508-c5aaf58c-2657-11e8-8ea9-ce2c5533dba2.png)

And here is the same review when used as shortcode:

![screen shot 2018-03-13 at 00 44 49](https://user-images.githubusercontent.com/3204558/37304615-196514f0-2658-11e8-9ca2-f83ffbef2548.png)

**Comment by selul** [comment]
@contactashish13 yes, you're right.

@contactashish13 when using the review post_type, can you hook to the wppr_name and alter it with post_title ?

**Comment by contactashish13** [comment]
@selul have addressed this. PR: https://github.com/Codeinwp/wp-product-review/pull/260

**Comment by selul** [comment]
@contactashish13 i've added one small comment.
