### ISSUE TITLE
Version 3.4.0 break validation for AMP Page ?

### ISSUE THREAD

**Issue by jeromeXoo** [Codeinwp/wp-product-review#249]
I'm not sure this plugin is causing the problem.

The problem :
- AMP pages are no longer valid

Error message :
The text (CDATA) inside tag 'style amp-custom' contains 'CSS !important', which is disallowed.

The CSS class concerned is: **#review-statistics** :
=>This CSS class is added to the AMP page

More information to come, I'm looking for. 

But if you can confirm that this CSS class is from this Plugin, that would be great.
=> Confirmed, this CSS class is from this Plugin ([https://github.com/Codeinwp/wp-product-review/blob/master/assets/css/frontpage.css](https://github.com/Codeinwp/wp-product-review/blob/master/assets/css/frontpage.css))

Rolling back to 3.4.0 => KO, the problem is still here
Rolling back to 3.3.2 => KO, the problem is still here

The affected AMP pages have the parameter "Is this a review post" = No

hum, it's crazy ... updated from 3.3.2 to 3.4.1 to return to the initial state.
=> AMP validation is now OK. #review-statistics is no longer in AMP page

I'm waiting for the confirmation in the google search console

**Comment by ineagu** [comment]
cc @selul @rohittm

**Comment by rohittm** [comment]
Thanks for reporting this to us. We are looking into this problem, and fix this soon.

**Comment by jeromeXoo** [comment]
Someone has the same error? it would help to isolate the problem

**Comment by selul** [comment]
@jeromeXoo should work fine now, you can update to the latest version.
