### ISSUE TITLE
UI issues with AMP

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/wp-product-review#251]
@selul 

Is the UI of this Multiple Review demo okay? 

https://demo.themeisle.com/wp-product-review/multiple-review-templates/amp/

**Comment by rohittm** [comment]
Also, https://demo.themeisle.com/wp-product-review/shortcode-review/amp/

**Comment by selul** [comment]
@rohittm yes, would be useful if you can tackle those, try to replicate on you instance the pages and track the issue. 

Be sure to validate the page using the amp validator.

**Comment by rohittm** [comment]
Sure. I'm on it.

**Comment by rohittm** [comment]
@selul seems like they have updated to new version and added new designs to their plugin and the new version is not compatible with wppr. https://ampforwp.com/demo/ working on that issue.

**Comment by rohittm** [comment]
@selul why do we have rating-amp.css?

**Comment by selul** [comment]
i challenge you to find out ⚔️

**Comment by rohittm** [comment]
Got it. It is used for filling circle according to the rating(s).

I asked it because CSS size is increasing and becomes more than the allowed CSS. We need to reduce more unused CSS.

**Comment by rohittm** [comment]
@selul PRs #257 and [Codeinwp/wp-product-review-pro#89](https://github.com/Codeinwp/wp-product-review-pro/pull/89)

All the templates, are now AMP compatible, and Shortcodes, as well. 

AMP will give validation errors if: 

- [ ] Multiple Reviews are used in one post (as all the CSS will be loaded and it will cross the AMP's size limit) in all four AMP designs (*Dashboard > AMP > Designs*)

- [ ] Shortcode Review ([The one in demo](https://demo.themeisle.com/wp-product-review/shortcode-review/amp)) is used with Design 3 of AMP (as Design 3 contains more CSS than other ones)

What more CSS can be reduced?

cc @HardeepAsrani

**Comment by selul** [comment]
@rohittm i've added some comments in the PR

**Comment by rohittm** [comment]
@selul I've replied to those comments. Check them.
