### ISSUE TITLE
Font Awesome Star Icons not showing up

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/wp-product-review#253]
@selul When I used both templates for WPPR, I wasn't able to see the star icons on both templates.

Template 1 (http://clever-lion.w5.poopy.life/2018/03/06/template-1/):

![screen shot 2018-03-06 at 22 27 42](https://user-images.githubusercontent.com/3204558/37046188-b94077f0-218d-11e8-827d-fa01bde2ab32.png)

Template 2 (http://clever-lion.w5.poopy.life/2018/03/06/template-2/):

![screen shot 2018-03-06 at 22 26 07](https://user-images.githubusercontent.com/3204558/37046204-c80c1fa0-218d-11e8-9e2a-f36c2cbb479a.png)

**Comment by rohittm** [comment]
I did this with the fresh install. When I selected star icon from WPPR settings, then it is showing fine!

**Comment by selul** [comment]
@contactashish13 can you check ?

**Comment by rohittm** [comment]
@contactashish13 So when I do a fresh install, I just create product reviews and the layout of both templates is like the one in first comment. When I go to settings and enable the custom icon (star), then it show the star icons. Let me know if you don't understand anything.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/wp-product-review/pull/255

**Comment by selul** [comment]
@contactashish13 i dont exactly understand the change, why we need to check the review template to enqueue that font awesome style ? It should not depend by the templates type and by the icon setting.

**Comment by contactashish13** [comment]
@selul as you can see in https://github.com/Codeinwp/wp-product-review/pull/255/commits/17bdf29c0e0ce6bb62de168800bd0ad7755dd025#diff-7fff6bc3802a0603710e8162a0bcdd99L117, the if condition already existed. Now I had a choice between

1. enabling star icon internally every time the user selects a template and not change the condition
2. using template as the condition

with 1, I wold need to check if the user was **not** already using a custom icon before changing the icon so I chose 2.

**Comment by selul** [comment]
@contactashish13 fair enough.

@rohittm can you check if all is working fine now ? Please make sure the default template behaviour is working as before.

**Comment by rohittm** [comment]
@selul I just tested this one, and every scenario (which was not working before), is now working fine.
