### ISSUE TITLE
add n/a for comment form

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#264]
@contactashish13 in the comment form, allow users to add  `N/A` when they leave a comment for a review post. 
This should be the default value. 

Also, make sure this won't affect the previous comment ratings.

**Comment by ineagu** [comment]
remember that before we had something in place so if a user didn't changed anything on those ratings it will be n/a. so if a user comment and doesn't change anything, we consider n/a automatically.

**Comment by contactashish13** [comment]
@selul I'm not sure I understand this issue. In a comment I can leave n/a or any random text, so I'm not sure what you mean by 
>allow users to add N/A

Are we disallowing users to leave n/a?

Also, what do you mean by this?
> make sure this won't affect the previous comment ratings.

**Comment by selul** [comment]
@contactashish13 i'm talking about the rating slider tied to the comment form. now if the user does not want to leave a comment, it will count as 0 rating.
The default option n/a, not zero as now.

Let me know if you got things clear.

**Comment by contactashish13** [comment]
@selul so are you saying the sliders should be able to provide a value of n/a instead of having the default value as 0?

**Comment by selul** [comment]
exactly. the intent is to allow user to not review when they leave a comment.

**Comment by contactashish13** [comment]
@selul my testing shows that it is considered a valid review only if at least one of the sliders has a non-zero value. So, if the user enters a comment and does not touch the sliders, it is not considered a valid review and thus does not affect rating. If the user uses any slider to enter a non-zero value, it is considered a valid review and affects rating. Do you want a different behavior?

**Comment by selul** [comment]
the thing is that if they play with the slider, there is no way to switch back to n/a. would be great if they move the slider to the most left position to be considered n/a, otherwise a valid rating.

**Comment by contactashish13** [comment]
@selul if they play with the slider and then move all sliders to 0, it becomes an invalid review. If they move all but one slider to 0, it is a valid review.

**Comment by ineagu** [comment]
Marius this thing with playing with the sliders is a non issue for me, they can refresh the page to go back to n/a then.

**Comment by selul** [comment]
@contactashish13 yes, but we need a more friendly solution otherwise way we need to provide each customer a tutorial on how they can teach their users to review.  
Showing them by default an 'N/A' string instead of zero, and allowing them to switch back to n/a will be better than now. 

I'm talking about a solution that's more friendly, the one that we have now indeed is working but needs a bit of fine-tuning to be understated.

**Comment by selul** [comment]
@contactashish13 @ineagu I will put this on hold and ask Rohit to make a doc on how users can send comments without reviewing the product.

**Comment by rohittm** [comment]
@selul I want to ask that while I'm using this feature, I can see that If I just use one slider for rating, the other options automatically becomes '0' and it effects the main ratings. I guess it is not the expected behaviour?
![screen shot 2018-03-26 at 22 15 40](https://user-images.githubusercontent.com/3204558/37920010-43dad15c-3143-11e8-9a65-618e9c03bcfd.png)

**Comment by selul** [comment]
yep, only if they don't review any of the option it should not save the ratings.
