### ISSUE TITLE
There should be option of fonts selection and/or inherit from the theme

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/wp-product-review#265]
@selul 
In [this](https://wordpress.org/support/topic/plugin-should-inherit-the-font-not-impose-it/) thread, the user wants to select fonts instead of using the fonts that comes with our plugin. They also want if they can use the same font that is used by the theme. Is this something we can work on?

**Comment by UVLabs** [comment]
I tried using inherit on the font of the review text but it didn't work maybe there's another way to approach this

**Comment by contactashish13** [comment]
@rodica-andronache I've removed explicit mentions of `font-family` from the public facing CSS files. The fonts should automatically inherit from the theme. 

PR: https://github.com/Codeinwp/wp-product-review/pull/285 and https://github.com/Codeinwp/wp-product-review-pro/pull/102

**Comment by rodica-andronache** [comment]
@contactashish13  I think there are still some font-family properties for #review-statistics for the first template

**Comment by contactashish13** [comment]
@rodica-andronache I don't think FontAwesome can be removed without extensive testing. Most often it is used for using the fa icons.

Here is what I find for font-family in the project:
![image](https://user-images.githubusercontent.com/12953439/40049266-df9ff9f2-5851-11e8-8d07-3240f66f8b65.png)

**Comment by rodica-andronache** [comment]
@contactashish13 yes,  it's mostly used for icons. But for me, the first template does not take the font family from the theme, just the other 2 templates. could you please check that?

**Comment by contactashish13** [comment]
@rodica-andronache It seems to be fine now. Can you please verify?

**Comment by rodica-andronache** [comment]
seems ok 👍
