### ISSUE TITLE
Support for BuddyPress

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/wp-product-review#272]
@selul According to this ticket in HS: https://secure.helpscout.net/conversation/553445906/158386/?folderId=212385 , there should be a support for BuddyPress as well for WPPR.

**Comment by rodica-andronache** [comment]
@rohittm here I would need you to actually test the plugin with BuddyPress and see what/if it's not working and it's making sense for us to do :) Let me know what you tried

**Comment by rodica-andronache** [comment]
@rohittm it's not very clear for me now what we should do :) From what I know there isn't a way for a user to add a review, unless by using that shortcode that'd be added just in the pro version. This is what you meant?
I would like to have a more clear idea of what BuddyPress offers and what we can do it the plugin. Maybe with some screenshots too.

**Comment by rohittm** [comment]
@rodica-andronache What I'm saying is, if on user registration, if a user has privileges to add a post, they can definitely add the review as the meta boxes are used in post edit option. Also, yes, they can add the reviews using shortcodes as well if they are using the pro version. The thing is there are ways to add a review from backend and not the frontend. I don't think there is anything we need to work upon for wppr to work with BuddyPress.
