### ISSUE TITLE
Custom icon not working on Style 1 template

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#273]
Custom icons aren't working on Style 1 template, but Stars appear regardless of what you define.
@selul

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/wp-product-review/pull/280

**Comment by rodica-andronache** [comment]
@contactashish13 for me it's not working for the third template now. Could you please check that too?

**Comment by contactashish13** [comment]
@rodica-andronache it works for me.

![image](https://user-images.githubusercontent.com/12953439/39989819-9da7aa00-5788-11e8-8270-d0a792f678ec.png)

**Comment by rodica-andronache** [comment]
for me not https://prnt.sc/jhm0q9 . @rohittm how about you? I have the 2.1.2 version for the pro plugin

**Comment by rohittm** [comment]
@rodica-andronache @contactashish13 @HardeepAsrani 

I tried all the cases, and everyone showed the desired icons. It works for me 👍
