### ISSUE TITLE
Check missing docs

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-product-review#275]
@rohittm I saw here https://wordpress.org/plugins/wp-product-review/ in the FAQ section, that some of the docs listed are not found.
for e.g
https://docs.themeisle.com/article/131-how-to-change-dynamically-the-name-of-the-review
Could you please check and see if you can add them back ( if they're still available ) or remove them from the listing? 👍 

Could you do this for Visualizer, Feedzy and Intergeo too? 

Plus, redo some of the screenshots? Saw many like this https://docs.themeisle.com/article/597-create-chart with that weird focused area.

Thanks

**Comment by rohittm** [comment]
@rodica-andronache 

### Missing Docs:

- [ ] https://docs.themeisle.com/article/131-how-to-change-dynamically-the-name-of-the-review
- [ ] https://docs.themeisle.com/article/210-how-to-fix-the-review-boxes-issue
- [ ] https://docs.themeisle.com/article/216-price-in-wp-product-review-is-messed-up

I wasn't able to find these docs on HS. Should we proceed adding those docs or remove them from the FAQ list?

I also saw that these options in FAQ are repeated twice, should I remove them?:

- [ ] How to change dynamically the image size for review
- [ ] WP Product Review how to change dynamically the option name format

For rest of the plugins, I'll create issues in their particular repositories.

### Images with weird focused area.

- None

**Comment by rohittm** [comment]
I also checked if the same issues are there in other plugins as well:

- Visualizer: [#254](https://github.com/Codeinwp/visualizer/issues/254)
- Pirate Forms: None
- Feedzy: None
- Intergeo: None

**Comment by rodica-andronache** [comment]
@rohittm 👍 
For the missing docs, maybe you can try to redo them if you can. I think the first one can be done, not sure about the other two, as they seem to be a bit specific to a certain issue. If you can't add them, let's remove them from the FAQ.
Regarding the two that are repeating, from what I've seen, there are different, no? I think you should leave them.

**Comment by rohittm** [comment]
@rodica-andronache I re-checked the repeated ones and those are the not different. I'll leave them as you say. And about the docs that are missing, I'm adding them.

**Comment by rohittm** [comment]
@rodica-andronache PR #276

**Comment by rohittm** [comment]
@rodica-andronache Can you check that doc again, and let me know if there's anything else that can be changed?

**Comment by rodica-andronache** [comment]
@rohittm I'm not able to access the plugin you created as an example https://drive.google.com/file/d/1r0pJBQVK9WMU5TWyBh4dU3tORkbSIG2E/view?usp=drive_web

**Comment by rohittm** [comment]
@rodica-andronache I didn't enable the sharing options, now you'll be able to access them.

**Comment by rodica-andronache** [comment]
@rohittm thanks, I was able to download the plugin, but I'm still not sure what this doc/plugin should do :D After installing the plugin, the Product Name option got empty and I can't add it back https://prnt.sc/j9w7y4 https://prnt.sc/j9w9cm . It's probably something in the plugin that I don't understand. could you please explain it a bit more? 😀

**Comment by rohittm** [comment]
I'll check with the plugin 😅

**Comment by rohittm** [comment]
@rodica-andronache I actually checked the code, and plugin is correct. The only problem is that it is updated when you update the post **twice**. I need help with the priority stuff. Can I get any help?

**Comment by rodica-andronache** [comment]
@rohittm I finally understood what this doc/plugin should do :D or at least I think so.
I think you can better explain in the doc the thing that the Product name ( from the wppr settings is displayed there ) and with this plugin, if you change the  title of the post, you can make it to dinamically change the product name too. 

and for the code, I think you need to change it like this:
`add_filter(` 'wppr_name','wppr_review_product_name_filter_demo',10,3 );

function wppr_review_product_name_filter_demo( $name, $id ) {
	// by default is used the cwp_rev_product_name meta field
	// you can use this filter to change it to the post title and add the proper formatting
	return apply_filters( 'wppr_review_product_name_html' , get_the_title( $id ) );
}`

because if you check how the filter is added in the plugin:
`apply_filters( 'wppr_name', $this->name, $this->ID, $this );`

there are 2 parameters

Let me know if it makes sense :D

**Comment by rohittm** [comment]
@rodica-andronache Thanks :) It works. Didn't notice the parameters thing. 
Updated the plugin and the doc. Here it is: https://docs.themeisle.com/article/874-how-to-change-dynamically-the-name-of-the-review

**Comment by rodica-andronache** [comment]
@rohittm please update the text too with more details like I mentioned, right now it's not very clear what this doc does, even with the plugin and the video 👍

**Comment by rohittm** [comment]
@rodica-andronache here: https://docs.themeisle.com/article/874-how-to-change-dynamically-the-name-of-the-review

Let me know if it is clear now :)
