### ISSUE TITLE
Update doc for Comparison Table

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-product-review#281]
@rohittm could you please check this doc https://docs.themeisle.com/article/424-wp-product-review-comparison-table-documentation and make sure it's updated? From what I've seen the options have changed for this

**Comment by rohittm** [comment]
@rodica-andronache done. Check it and let me know about any changes (if any) that can be done.
https://docs.themeisle.com/article/424-wp-product-review-comparison-table-documentation

**Comment by rodica-andronache** [comment]
looking good 👍
