### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/wp-product-review#288]
@rohittm Like for feedzy, we want to add real life code examples for all hooks used here.

Some inspirations:
- https://secure.helpscout.net/conversation/541489037/157083/?folderId=212390#thread-1477246864
- https://secure.helpscout.net/conversation/534663480/156240/?folderId=212390#thread-1460606289

CC: @rodica-andronache

**Comment by rohittm** [comment]
@contactashish13 what we want here is to add docs like: "How to manually change the length of description in comparison table", etc.?

**Comment by contactashish13** [comment]
@rohittm yes, that could be one. We can obviously not cover all possible use cases but one per hook should be fine to begin with. The intent is for users with basic PHP knowledge to understand how to go about using the hook because in most hooks it is not apparent what the arguments refer to or how to use those arguments. So the example will make it clearer. 

Suggestions @rodica-andronache ?

**Comment by rodica-andronache** [comment]
@rohittm @contactashish13 I see we have this https://docs.themeisle.com/article/770-what-actions-and-filters-are-available-in-wp-product-review
Maybe it would be a good idea to check if it contains all the hooks/filters and make sure it's updated. And for all ( or the most important ) also create some separate docs like you suggested "How to manually change the length of description in comparison table" and link them in the main doc, as an example for each specific hook/filter.
What do you think?

**Comment by rohittm** [comment]
@rodica-andronache That seems fine. So, here's what I need to do:

1. Check and/or update or the filters and actions available.
2. Create example docs for each hook.

Let me know if there's anything, I'm missing. 
cc @contactashish13

**Comment by rodica-andronache** [comment]
seems ok for me 👍

**Comment by rodica-andronache** [comment]
@rohittm how is this going? 💯

**Comment by rohittm** [comment]
@rodica-andronache I've been adding examples. You can see docs for few filters I have added them. I'll be completing them this week.

**Comment by mileamadalin** [comment]
@contactashish13 Yep, I will add a notification in the docs channel

**Comment by mileamadalin** [comment]
@contactashish13 here is the link with the doc https://docs.themeisle.com/article/969-in-wppr-how-do-i 

Let us know if there is anything else we can improve
