### ISSUE TITLE
Custom image size for widget

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-product-review#292]
https://wordpress.org/support/topic/widget-image-size/

**Comment by contactashish13** [comment]
@rodica-andronache I think the the best way to achieve this is to download the image instead of referencing it directly and upload it so that it creates 3 sizes. Should this be the behavior by default or should this be an opt-in behavior using settings?

**Comment by rodica-andronache** [comment]
@contactashish13 from what I've seen, the image is displayed using get_small_thumbnail() which is taking the thumbnail size https://prnt.sc/jwro50. So, if the user would change it to 50 there, it would make 50x50.
But that is used in other places too https://prnt.sc/jwrorw.
If the only problem is in the widget, I would think I would register another image size of 50x50, and use just there. What do you think?

**Comment by contactashish13** [comment]
@rodica-andronache There are 2 more scenarios:

- This image is used in the review post as well not just in the widget. Should we use the thumbnail image here or a 50x50 image?
-  We allow users to specify a URL for the image if they don't want to upload using the media library. This might also create similar problems. I think in this case we should automatically upload the image rather than referencing the URL directly.

Also, we don't need to register a new image size. We can use the filter `wppr_review_image_size` and provide 50x50 as the size. This should generate the 50x50 image on the fly. (I tried on my dev instance where the thumbnail size is specified as 150x150. When I provide 50x50 it gives me a 100x100 image, don't know why. If I don't use the filter, it gives me a 150x150 image)

Let me know what you think.

**Comment by rodica-andronache** [comment]
@contactashish13 we should use the 50x50 size only where it makes sense. For the review post is doesn't, from what I've seen.
If they specify a URL, don't think we should change that, they can enter whatever they want.
So, we can either register a new image size or use the filter you mentioned. Related to this https://github.com/Codeinwp/wp-product-review-pro/issues/111

**Comment by rodica-andronache** [comment]
@contactashish13 is this working for you? Because for me it's not working. 
What I think you need to do it register the image size with add_image_size and adapt the get_small_thumbnail() function , or create a new one, that should use that image size, and use it for the widget

**Comment by contactashish13** [comment]
@rodica-andronache it works for me - https://github.com/Codeinwp/wp-product-review/issues/292#issuecomment-399826896

We do not need to register a new image size. Can you please review the code if you feel my approach is incorrect?

**Comment by rodica-andronache** [comment]
@contactashish13 I think the image size needs to be registered because with the current code when regenerating the thumbnails, indeed it tries to get the image by 50x50 but it can't do it, as that image size does not exist.
If it's really working in your case, it means that on your wp instance you have a 50x50 image size ( from another plugin or as a thumbnail size (https://prnt.sc/k3b5ns but this would apply across the site)

For example, in my case, the image for the widget appears as 100x100 because is the closest I have registered ( from a plugin )
https://prnt.sc/k3b54p
and if you read here https://wordpress.stackexchange.com/questions/11547/why-is-wp-get-attachment-image-src-not-working-with-my-custom-size-add-image-si/11554 (it is actually just mapping to the closest thumbnail size that has already been generated)

This is what I think is happening. Let me know your thoughts 👍

**Comment by rodica-andronache** [comment]
@contactashish13 thanks, but I'm not sure how it's working for you. For me, it's working only if I change in class-wppr-widget-abstract.php in the image_size() function, and return 'wppr-widget'.
But this needs to be adapted, as by just leaving it there, it's changing the image size on single product pages too.
Let me know your thoughts 👍

**Comment by contactashish13** [comment]
@rodica-andronache whether you send an array of 50x50 or `wppr-widget` both should work the same.  Nevertheless, I have changed it to be consistent.

I don't see the problem with single product page.

![image](https://user-images.githubusercontent.com/12953439/42638409-2ff9955c-860b-11e8-8d26-9de54cf05867.png)

**Comment by rodica-andronache** [comment]
@contactashish13 is that image in the widget really 50x50? And are you sure you don't have that image size registered from another plugin or from the thumbnail?
I'm asking because like I said for me it's not working? :)

**Comment by contactashish13** [comment]
If that were the case my previous tests would have given me a 50x50 image and not a 100x100 image :)
