### ISSUE TITLE
Price is shoved to the left, next to the title

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/wp-product-review#294]
ref:
https://secure.helpscout.net/conversation/599853539/163544
https://secure.helpscout.net/conversation/599305732/163493

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/wp-product-review/pull/295. I've created this against master in case you want to make an immediate release.

@rohittm this was inadvertently introduced here https://github.com/Codeinwp/wp-product-review/commit/8f67b2f78dbb4eaeec29f16f2c97107a141e5e08#diff-7794939a35bcdfd3112a3892cd5b667f. You did the right thing but maybe you can test a bit as well after making any changes however small?

**Comment by rodica-andronache** [comment]
@contactashish13 thank you 👍 It's released now.

**Comment by Vishakha-Patel** [comment]
It seems this change is reverted - https://secure.helpscout.net/conversation/621661053/165910?folderId=948378 :(

@contactashish13 @rodica-andronache

**Comment by UVLabs** [comment]
@rodica-andronache @contactashish13 i fixed this a few days ago here: https://github.com/Codeinwp/wp-product-review/pull/302

**Comment by rodica-andronache** [comment]
Yes, probably  I missed it. Thanks, it should be ok now :)
