### ISSUE TITLE
Top Products in Category

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/wp-product-review#30]
O cerere putin mai ciudata, dar care are sens. 
Un widget care afiseaza top x produse din categoria din care articolul curent face parte. 
Se complica putin lucrurile, mai ales cand widgetul va fi pe pagini care nu sunt in categorii cu review-uri, dar am zis sa pun aici spre dezbatere :)

**Comment by selu91** [comment]
exista in ultimele versiuni
