### ISSUE TITLE
User Feedback - change include file method

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/wp-product-review#305]
The issue is explained in detail here - https://wordpress.org/support/topic/version-3-4-6-disables-wordpress-login-because-of-an-error/

@contactashish13

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/wp-product-review/pull/332

**Comment by Vishakha-Patel** [comment]
Hey Ashish,

This was on the user's website/hosting. It did not occur on my local. So I am not sure how to test this one. 

However, I tested the plugin with the PR commit and the plugin is working fine now as well.
