### ISSUE TITLE
dist folder is present in master branch

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-product-review#318]
@contactashish13 it seems someone remove from gitignore the dist folder and it's present in the master branch too. 

https://github.com/Codeinwp/wp-product-review/tree/master/dist

this should be removed from distignore file too https://github.com/Codeinwp/wp-product-review/blob/master/.distignore 

as on release will be packed in the zip file for distribution.

**Comment by selul** [comment]
@HardeepAsrani it seems you did it -> https://github.com/Codeinwp/wp-product-review/commit/ec62af1286016c46c4ec84f331b6d9cff8212616#diff-51b77af537e37fbcbab72a3bd0dad7c5

**Comment by HardeepAsrani** [comment]
Yea, seems to be a lot of confusing with Gutenberg also using `dist` folder. I'll use better selector.

**Comment by selul** [comment]
@HardeepAsrani yes, i saw that you did this awhile for feedzy too and i've reverted by renaming the gutenberg dist folder, i think we can do the same thing here.
