### ISSUE TITLE
Review categories not working

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/wp-product-review#320]
@contactashish13 The review category archive pages always show “No results found” even when there are posts in that category. Screenshots: http://prntscr.com/l3jszr http://prntscr.com/l3jt73
https://wordpress.org/support/topic/review-categories-not-working/#post-10759775

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/wp-product-review/pull/321

@poonam279 can you please test?

**Comment by poonam279** [comment]
@contactashish13 Tested. It's working.
