### ISSUE TITLE
Support different review types/schemas

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/wp-product-review#322]
review types - books, movies, tv shows etc. with dedicated templates, specific json-ld schema

**Comment by contactashish13** [comment]
### movie/tv shows
- we can use use http://www.omdbapi.com/ for API
- the most popular plugin for this type is https://wordpress.org/plugins/wpmovielibrary/ which doesnt seem to be very needed, was last updated a year ago and has only a 1000+ installs... so do we even need to support this type?

### books
- we can use https://isbndb.com/
- the top plugins are https://wordpress.org/plugins/wpbooklist/, https://wordpress.org/plugins/book-review/ and https://wordpress.org/plugins/recencio-book-reviews/ and none of them have more than 1000+ installs... so do we even need to support this type?

I think a generic way we can support multiple review types could be as below:
- the user can specify what type of review this is (movie, book etc.)
- the user can provide provide 
* a JSON object
* URL that gives a JSON object
* a text search string (that uses the API corresponding to the review type)
- we parse the object
- we populate the schema on the basis of that
- we can also provide out of the box templates for each review type

@selul @ineagu suggestions?

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/365

- In the review meta box, the review type would be product by default and can be changed to show a different review type.
![image](https://user-images.githubusercontent.com/12953439/51300019-75594000-1a50-11e9-9714-53e7fbef5fc9.png)

- The fields of each review type will be populated and their visibility can be toggled
![image](https://user-images.githubusercontent.com/12953439/51299980-4642ce80-1a50-11e9-8303-7ad46f1ef987.png)
![image](https://user-images.githubusercontent.com/12953439/51300060-9e79d080-1a50-11e9-93f2-5fe8ff9acde1.png)

- All values that are filled up will then be shown in the LD JSON schema as part of the selected review type

@selul can you please review this?

**Comment by poonam279** [comment]
@contactashish13 A user on wp.org reported something related to schema implementation. https://wordpress.org/support/topic/schema-implementation-upgrade/
If it's not related to this thread please let me know so I can create a new issue.

**Comment by contactashish13** [comment]
@poonam279 you on the right issue :) you can let him know that we will be releasing this soon

**Comment by poonam279** [comment]
@contactashish13 when we are going to release this feature? A user wants to purchase the pro version but before that, he wants to know when will this issue get resolved.

**Comment by contactashish13** [comment]
@poonam279 you can let him know to expect this release around the time of the release of WP 5.2 (mid to late April). If he wants to help us test this feature before the release, we can share a zip file of the plugin with him by Monday.

**Comment by contactashish13** [comment]
### Warnings in  Google Structured Data Testing Tool 

Most review types will show no warnings when tested with the Google Structured Data Testing Tool **except** all children of `Product` viz.
- Product
- IndividualProduct
- ProductModel
- Vehicle
- SomeProducts

This is because they `offers` element is not being populated completely by the plugin. This can be addressed by using the filter `wppr_schema`

**Comment by radu-themeisle** [comment]
- I tested with the Book type and I don't see all the fields I've filled in: http://prntscr.com/nlh5uz
The fields that are missing: alternateName, award, bookEdition, contentRating, copyrightYear, genre, isbn, material, numberOfPages, typicalAgeRange
These fields are not filled with my text: description, name

- I can't access this menu in the Block Editor, does it not have support for it? If not, it should, we can't have the menu available just for the users who use the Classic Editor.

**Comment by contactashish13** [comment]
@radu-themeisle looks like the editor displays some fields that are not actually part of the schema definition. Thats why when you see the schema in the tool, those fields are ignored. Need to check why they show up in the editor at all.

**Comment by contactashish13** [comment]
@radu-themeisle the first issue is addressed by https://github.com/Codeinwp/wp-product-review/pull/399

PS - Hardeep will add this feature in Gutenberg at a later date.
