### ISSUE TITLE
If scripts aren't able to load in the WP editor and the post/page is saved, review details are lost

### ISSUE THREAD

**Issue by samglover** [Codeinwp/wp-product-review#367]
In trying to optimize our page speed, I dequeued the WP Review Pro scripts from pages they weren't needed on (we have a page template we use for all product pages, and don't use WP Review Pro on any other pages). It seemed to work fine until we updated and saved a page. On save, the review details were wiped from the page. In other words, we had several features on each page, with point ratings for each feature. If we saved the page while scripts were disabled, both the features and the rating were deleted from the post (and from the postmeta table in the database—they were completely lost as far as I can tell).

Once I realized what the problem was, I un-dequeued the WP Review Pro scripts from admin pages, and we were able to use features and ratings again, but we had to recreate them from scratch.

(Related gripe: WP Review Pro loads a TON of scripts whether or not reviews are enabled on the post.)

**Comment by contactashish13** [comment]
@samglover thank you for your feedback. Would you be able to share screenshots of the page/console where you feel WPPR is loading scripts even when it is not supposed to? We would definitely want to improve on that.

**Comment by samglover** [comment]
Sure thing. This is our homepage (lawyerist.com) showing all the scripts WP Review Pro loads (or tries to load) even though neither comments nor reviews are enabled for that page.

Our defaults are set to no review, custom location, and user ratings disabled.

<img width="1440" alt="screen shot 2019-02-11 at 8 52 33 am" src="https://user-images.githubusercontent.com/2208482/52571194-b38d1980-2dda-11e9-80ca-dc7d4146e4db.png">

<img width="1440" alt="screen shot 2019-02-11 at 8 52 57 am" src="https://user-images.githubusercontent.com/2208482/52571200-b5ef7380-2dda-11e9-8cb0-0e7304a764fc.png">

**Comment by contactashish13** [comment]
@samglover I think you have WP Product Review Lite/Pro confused with WP Review Pro - its the latter that is loading the scripts and that does not belong to our portfolio. Can you please verify? You may want to try our plugin as well, as we don't load stuff that is not required :)

**Comment by samglover** [comment]
Whoops!
