### ISSUE TITLE
Replace FontAwesome with Dashicons

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/wp-product-review#392]
A user pointed out that the half-empty and empty star icons are not visible and I pinpointed the issue is coming from the Avada theme which seems to have switched to Font Awesome 5 and by using the new font-family it breaks those 2 icons:
http://prntscr.com/ndi7oo
https://secure.helpscout.net/mailbox/dd8c59516d047fb2/212385/

I have asked the user to also contact Avada so we can see if they plan to add backwards compatibility, but I'm also thinking if it won't be better to bundle the icons that users can choose (they are 10 I think) into the the plugin and remove FA enqueue.

**Comment by radu-themeisle** [comment]
@contactashish13 I believe the solution of using Dashicons is the best course of action.
I tested PR #389 and noticed that only one style applies the dasicon star, the others take on the icon set in the settings.
I was expecting we replace FA with Dashicons entirely and remove FA from the plugin. What do you think?
Also, does the "[Disable Font Awesome](http://prntscr.com/nipbny)" option work? I enabled it and the font-family FontAwesome was still applied by a class from the plugin.

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/wp-product-review-pro/pull/188 and https://github.com/Codeinwp/wp-product-review/pull/389 
- replace FontAwesome with Dashicons
- removes the modal popup for icons and shows them inline (https://github.com/Codeinwp/wp-product-review-pro/issues/172)
- if the user has chosen a FontAwesome icon and upgrades to either new lite or new pro, the review does not break and keeps showing the FontAwesome icon chosen

**Comment by contactashish13** [comment]
@radu-themeisle can you please test this?

**Comment by radu-themeisle** [comment]
- Please check this PHP [error](http://prntscr.com/nl185j), it's not related to the theme, I've seen it also when using twentyninteen.
- I changed the star dashicon to an FA icon but it didn't change it on the frontend, I could still see the star icon.
 -Can you add a check sign (✔️) once the settings finish [saving](http://prntscr.com/nl1aag)? There's no feedback to show the process has finished. (if it's not a quick solution for this let me know so I can add an issue)

**Comment by contactashish13** [comment]
@radu-themeisle the PHP error should be okay now. 

> I changed the star dashicon to an FA icon

I'm not sure I understand this. We are replacing all instance of FA with dashicons and not the other way around. Can you explain what you wanted to do there?

PS - when the options are saved the loading indicator next to the button vanishes. Maybe it can be made more intuitive. You can create a new issue for that.

**Comment by radu-themeisle** [comment]
- PHP error gone ✔️ 
- _"I changed the star dashicon to an FA icon"_ it seems to work now, my point was that I changed the  rating icon but in the review the icon was still the dashicon star.
-  _"the options are saved"_ I opened an [issue](https://github.com/Codeinwp/wp-product-review/issues/398).

**Comment by radu-themeisle** [comment]
I forgot to give you feedback on the **inline icon rating picker** . I really like what you've done there, simple and clear: http://prntscr.com/nlk1ge 👍
