### ISSUE TITLE
Manually placed option for review box should only show when pro enabled

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/wp-product-review#393]
@contactashish13 The manually placed option for review box(http://prntscr.com/niq9ej) works only in premium version so the user who uses lite version only thinks that there is an issue or bug because nothing happens after choosing this option. I think we need to disable or freeze this button in Lite and putting a tooltip or message that says the option is available in Pro. 

EDIT: All other options (before content and after content) should show up all the time

cc @radu-themeisle

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/395 and https://github.com/Codeinwp/wp-product-review-pro/pull/189

**Comment by radu-themeisle** [comment]
@contactashish13 the Review Position box [is gone](http://prntscr.com/nkyhnn) in the lite version. Can you check as I believe only the option to choose "manually placed" should not be present in the lite version, but the "before/after" content should still be available.
Regarding the doc it has to be updated but not before releasing the update with this "fix".

**Comment by contactashish13** [comment]
@radu-themeisle you are right! :cry:  

I've fixed this with https://github.com/Codeinwp/wp-product-review/pull/396 (https://github.com/Codeinwp/wp-product-review-pro/pull/190 is to revert the change in PRO)
