### ISSUE TITLE
li before issues

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-product-review#40]
Need ot make sure the before element is empty inside the review box li's .

**Comment by selu91** [comment]
nu prea inteleg la ce te referi aici

**Comment by ineagu** [comment]
erau niste teme care aveau ceva de genu in css pt widgets : 

li::before { 
    content: "Read this: ";
}

Ar trebui sa ne asiguram din plugin ca pt review/widget pseudo-elementul before e gol.
