### ISSUE TITLE
add the getting started video to the welcome page

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/wp-product-review#403]
@contactashish13 we can add this video after the activation of the plugin in a welcome page like we do for the other plugins

> https://www.youtube.com/watch?v=vEBgeIYY8UM

**Comment by contactashish13** [comment]
@dascalescuro can you please let me know what copy you want next to the video? I've provided some basic text but I'm sure a lot more would be better.

![image](https://user-images.githubusercontent.com/12953439/59018653-05fbb580-8864-11e9-945f-3faf514a118b.png)

**Comment by dascalescuro** [comment]
Here is my take on the copy you can add next to the video.
Let me know if you need other resources.

=============

<h1>Welcome to WP Product Review</h1>

WPPR makes it easy to create review posts in WordPress. We recommend watching this Getting started video, and then try the plugin for yourself by enabling the review post option in the post Document sidebar.

 You can also read our guide on how to set up and create your first review.

<button>Read the documentation</button>

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/416
