### ISSUE TITLE
Schema error: Unspecified Type (The @type is required and cannot be an empty string.)

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/wp-product-review#405]
If we test review on structured data testing tool, it shows an error. I checked demo and it shows error as well - https://search.google.com/structured-data/testing-tool/u/0/?url=http%253A#url=https%3A%2F%2Fdemo.themeisle.com%2Fwp-product-review%2Fcustom-icons%2F

Ticket: https://secure.helpscout.net/conversation/854998093/188904?folderId=212385

@contactashish13

**Comment by contactashish13** [comment]
@Vishakha-Patel @mileamadalin the new version 3.6.1 addresses this
