### ISSUE TITLE
Number of options/pros/cons goes back to default (3) after being set

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/wp-product-review#406]
From the WordPress Dashboard > Product Review > General Settings.
The Number of options/pros/cons goes back to number 3 even after it has been set to a different number. This happens both on free and premium version.

https://secure.helpscout.net/conversation/857398096/189163/
https://secure.helpscout.net/conversation/855774644/189002?folderId=212385

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/wp-product-review/pull/407

The problem was with all select boxes that had numeral values (e.g. visitor influence). Related to changes done for #386

**Comment by contactashish13** [comment]
@purplecodes @radu-themeisle @mileamadalin the new version 3.6.1 addresses this
