### ISSUE TITLE
Structured Data issue

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/wp-product-review#41]
Rich Snippets functioneaza, dar nu optim.

Codul nu e validat de checker-ul de la google: https://developers.google.com/webmasters/structured-data/testing-tool/?url=http://dev2.themeisle.com/reviewgine/?p=11

**Comment by mariusghitulescu** [comment]
Si aici un exemplu cand e inclus is pretul: https://secure.helpscout.net/conversation/76095312/17269/

**Comment by selu91** [comment]
2.6.1 rezolva asta, folosim acum rich snippets de la google.
