### ISSUE TITLE
Clearfix class conflicts with some themes

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/wp-product-review#437]
In some themes (Donovan in this case) that use flex the clearfix class from the plugin can cause display issue because it adds `display: block` with a higher priority: http://prntscr.com/ohb9dp
This how the theme should look: http://prntscr.com/ohba20

Overriding that class for the header is a temporary fix.

**Comment by contactashish13** [comment]
closing this in preference to #438
