### ISSUE TITLE
Star ratings in Google search no longer visible in v3.7.0

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/wp-product-review#440]
Tested the user's review URL on Google's Structured Data Testing Tool and got errors:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fcannabisvapelife.com%2Fhoneystick-beekeeper-vape-review%2F

Tested on my own with the latest version and also see the errors.

@contactashish13 

Ticket: https://secure.helpscout.net/conversation/906940839/196959?folderId=212385

**Comment by contactashish13** [comment]
@purplecodes is this different from https://github.com/Codeinwp/wp-product-review/issues/412?

**Comment by purplecodes** [comment]
@contactashish13 

This is similar to that issue.

**Comment by contactashish13** [comment]
@purplecodes then it is not an issue. Please read https://github.com/Codeinwp/wp-product-review/issues/322#issuecomment-484783491. This is for everyone in the support team @Codeinwp/support. @purplecodes please close this once you read
