### ISSUE TITLE
External CSS not allowed in AMP

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/wp-product-review#446]
ref https://wordpress.org/support/topic/amp-validation-error-dashicons/

Also true for pages such as https://demo.themeisle.com/wp-product-review/shortcode-review/amp/

![image](https://user-images.githubusercontent.com/12953439/63929743-99154780-ca6f-11e9-9115-542247439990.png)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/447

**Comment by stefan-cotitosu** [comment]
Adding the link to the ticket so I can notify the user when this is fixed and released.
https://secure.helpscout.net/conversation/963338608/202500/
