### ISSUE TITLE
Pros and Cons text headings do not show up in polylang

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/wp-product-review#456]
https://wordpress.org/support/topic/translate-pros-cons-in-polylang/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/457

**Comment by rodica-andronache** [comment]
@contactashish13 not sure how you've tested this, but for me, the strings don't appear in **Languages > Strings translations** in Polylang's settings, unless I add the **wpml-config.xml** file with this content
`<wpml-config>
    <admin-texts>
        <key name="cwppos_options">
            <key name="cwppos_pros_text" />
            <key name="cwppos_cons_text" />
        </key>
    </admin-texts>
</wpml-config>`

as mentioned here https://polylang.pro/doc/the-wpml-config-xml-file/

**Comment by contactashish13** [comment]
@rodica-andronache I believe this is because the text value is part of the plugin's settings and is not being set in the .POT file. I don't know if polylang supports such dynamic text translation.

**Comment by rodica-andronache** [comment]
@contactashish13 from what I know from themes, dynamic strings are translated using the `wpml-config.xml` file I've mentioned. You can check it out

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/wp-product-review/pull/472 adds the `wpml-config.xml` to the root **without** the changes in #457. @rodica-andronache I think we can close #457 and use #472 instead.
