### ISSUE TITLE
CSS conflict with BuddyPress

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#49]
Source: https://wordpress.org/support/topic/css-conflict-with-buddypress

@ineagu 

Hi,

I'm using latest versions of Buddypress (2.2.0) and WP Product Review (2.4.9). When I am on Settings > Buddypress, I can't see submit button for the forms, because the buddypress submit button is wrapped in `<p class="submit clear">` and your css dashboard_styles.css line 31, is defining the class clear like this:

```
.clear {
    clear:both;
    display:block;
    overflow:hidden;
    visibility:hidden;
    width:0;
    height:0
}
```

Can you do something to avoid this conflict? Maybe load your css only when you need it, or use a more specific name for clear?

Thanks!

**Comment by selu91** [comment]
solved in 2.6.3
