### ISSUE TITLE
Update backlinks on wp.org

### ISSUE THREAD

**Issue by adelina17** [Codeinwp/wp-product-review#496]
Hey @contactashish13 

We need to update a few links here: https://wordpress.org/plugins/wp-product-review/

These are the links that have to be corrected: http://prntscr.com/tl9qtf

From http://www.codeinwp.com/blog/fastest-wordpress-hosting/ to https://www.codeinwp.com/blog/fastest-wordpress-hosting/
And from http://www.codeinwp.com/blog/15-best-wordpress-review-themes/ to https://www.codeinwp.com/blog/best-wordpress-review-themes/

Please let me know when it's done. Thanks! :)

cc @rodica-andronache

**Comment by contactashish13** [comment]
@adelina17 done. Can you please close this issue when you verify it is okay?

**Comment by adelina17** [comment]
All good, thanks!
