### ISSUE TITLE
Undefined variable nr_of_comments

### ISSUE THREAD

**Issue by robi09** [Codeinwp/wp-product-review#50]
Cateva mici erori descoperite cat am lucrat pe plugin.
Am atasat imaginile, @ineagu asignezi tu mai departe la cine trebuie.
![error1](https://cloud.githubusercontent.com/assets/4840427/6166997/da23085c-b2be-11e4-891b-726c607cbb2c.PNG)
![error2](https://cloud.githubusercontent.com/assets/4840427/6166998/da237058-b2be-11e4-905c-ca2722effbbd.PNG)

**Comment by selu91** [comment]
s-a rezolvat in 2.6.1
