### ISSUE TITLE
Migration to Otter

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#503]
The Product Review block is currently under review for initial version so it's about time to plan the migration from WPPR: https://github.com/Codeinwp/gutenberg-blocks/issues/635

@selul Do you have any thoughts on how this should be done?

- Should we have an option for users to migrate in the editor?

- An automatic migration with one button?
  - Possible issue with this is that WPPR usually does more than Otter's block, so people might lose some functionality if we do automatic migration.
  

So yea, how do you think we should approach this?

**Comment by selul** [comment]
@HardeepAsrani this is how I see it: 

1. In Otter general settings we can a toggle which enables the migration feature. We can **show** this only if we detect that they used wppr before ( checking by common wppr options or similar ) and make that toggle by default **on**. 
2. Once the feature is enabled, on pages/posts where we detect reviews that were previously created with wppr, when they add the otter review block we show a button to migrate to this block the current review settings. Moreover, if we can import wppr reviews from other posts/pages, would be huge.
3. We can migrate what options are compatible with the new block, it's still better than starting from zero. 
4. On a separate note, we can add a notice into wppr that we have migrated functionality in otter for block editor. 

Let me know what do you think.

**Comment by HardeepAsrani** [comment]
Okay, so it seems some good feedback. Here's what we can add:

- No need to add any toggle to Settings for normal migration help. We can check these things on the post instead of the site.
- If you have WPPR, we will display the "Migrate to Block" button in the Review Sidebar or if you add a Review block.
- If you don't have WPPR active, we can just give Migrate to Block if the post uses any meta fields.
- In both spots, we can link to a document detailing the changes, so people know the choice they're making and the options they might lose.
- Once they migrate, we disable the WPPR review meta.
- If someone has WPPR + Otter activated, we also show them notice when they try to make a new review with WPPR informing them about the change.
- Apart from that, we can have an option to allow "Automatic Migration" in which we take meta from the post and add the block to the end of the post. We won't do this at the moment but on the first-page load. In this, we can have some checkboxes for them to click which will let them know things that won't be migrated so they don't complain later. We won't delete any metadata of WPPR, just disable the post review.

One issue here is that people if using the Comparison Table extension, the table might stop working. I suppose we can do that now that we don't sell the extension? Of course, in some time we will include our own Comparison table to Otter for Neve Pro users.

What do you think @selul?

**Comment by selul** [comment]
I agree with the Automatic Migration, I wont add either an option for it, just to have the manual migration mechanism should be enough. 


> No need to add any toggle to Settings for normal migration help. We can check these things on the post instead of the site.

What happens if they don't want to migrate, the notice being over and over showing up for them will be kind of annoying. That's why I think a toggle to enable the migration helper would be helpful, which can be by default on.

`Once they migrate, we disable the WPPR review meta.`

This should be good, just to make sure to not remove the wppr data, in case that they want to switch back.

**Comment by HardeepAsrani** [comment]
> I agree with the Automatic Migration, I wont add either an option for it, just to have the manual migration mechanism should be enough.

I don’t understand what you meant. Should we have an automatic option or not?

> What happens if they don't want to migrate, the notice being over and over showing up for them will be kind of annoying.

We won’t show them any such notice in the editor after first attempt. Can save their disabled click on transient. If they disable we won’t show any notice, just a migrate button that they need not use.

Will make sure it’s not intrusive after first attempt.

**Comment by selul** [comment]
> I don’t understand what you meant. Should we have an automatic option or not?

Let's not do it for now.

> Will make sure it’s not intrusive after first attempt.

Still, this will be there. We can review this at the end and see how it looks.

**Comment by HardeepAsrani** [comment]
This is almost done, I'll post a video tomorrow so you can see if this current workflow is good for you. One thing, do you want to show a notice for Install Otter on Dashboard or just WPPR page? They will see it on Editor if they go to edit/create review, so we want to show it on Dashboard (or Options page) too or Editor is enough? @selul
