### ISSUE TITLE
Featured Image

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/wp-product-review#53]
@ineagu aici sunt modificarile facute pentru a rezolva problema cu featured image, daca poti arunca un ochi sa-mi confirmi ca e bine sa dau un Pull Request

https://themeisle.com/forums/topic/freature-image-is-not-showing-up-on-pro-version/page/2/#post-86907

**Comment by mariusghitulescu** [comment]
Am mai facut acum niste modificari, ca sa foloseasca thumbnail in loc de full featured image.

**Comment by ineagu** [comment]
vad ca ai schimbat complet logica if-ului aluia, stiu ca era ceva dubios, dar rezolvasem, pare modificat mai mult decat thumbnail

**Comment by ineagu** [comment]
@mariusghitulescu imi poti pune un task pe redbooth sa ma uit aici ? si in principiu cand tre sa fac ceva, pe git sunt multe si nu tot timpul le vad

**Comment by mariusghitulescu** [comment]
Still broken.

**Comment by selu91** [comment]
am rezolvat pe 2.6.2
