### ISSUE TITLE
Error in adminOptionsValidator.php

### ISSUE THREAD

**Issue by vncatalin** [Codeinwp/wp-product-review#54]
La 2.5.2 am luat eroarea asta la activare, nu stiu insa daca a fost raportata pana acum problema.

![2015-03-13_10-39-22](https://cloud.githubusercontent.com/assets/818818/6635455/ed9d60e6-c96e-11e4-8e35-193b2587f252.png)

**Comment by selu91** [comment]
s-a rezolvat in 2.6.3
