### ISSUE TITLE
The product name goes under the image 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-product-review#55]
@rodica-andronache @ineagu  I received this message from a client:

"I'm just noticing that the formatting when the product name is a bit long, goes under the image of the vote, and if it wraps, it goes under the picture...not really nice...

n.1 BEATS Studio Wireless (perfect formatting)
n.2 SENNHEISER Momentum On-Ear (text under the vote and wrapped under the picture)
n.3 BOSE QuietComfort 20i (text really close to the vote)"

![screen shot 2015-03-25 at 08 53 12](https://cloud.githubusercontent.com/assets/6906834/6843380/9156e9fe-d3a2-11e4-9c87-e44d478042c6.png)

**Comment by selu91** [comment]
s-a rezolvat in 2.6.3
