### ISSUE TITLE
Need quite a bit of improvement

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#56]
Source: https://wordpress.org/support/topic/need-quite-a-bit-of-improvement

Hi, this is a great plugin, but a quite a bit of improvement is needed in your plugin to make it even more awesome. I'm posting the needed improvements below as posint basis. Please try to update your plugin with the best coding practices and so that it doesn't slow down the site loading time.

    Load javascripts in the footer. (very very important)
    Load plugin JS files asynchronously if possible.
    Use rel="nofollow" for the anchor tag of image and button.
    Make fontawesome loading optional. As many themes now a days comes with built in fontawesome, so there is no need to add yours, because it will increase a file load and have to execute by the browser. It's better you put a radio box in the plugin setting asking the user whether or not he wanna add fontawesome and then do simnple php if else in your code.
    Its better if you load minified version of your CSS and JS files on the site, it will make your plugin lightweight and will help to load faster.

I'm looking forward to see these fixes in the recent update of this plugin. These minor changes will take your plugin to the next level. Also many many thanks for building this awesome plugin.

@ineagu

**Comment by selu91** [comment]
the latest version of 2.6.3 add this features.
