### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by robi09** [Codeinwp/wp-product-review#58]
Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected T_STRING in /home/tehnorev/public_html/wp-content/plugins/wp-product-review/inc/cwp_frontpage.php on line 1

Hi guys, Andrei de la simplenet.ro mi-a raportat eroare de mai sus, a intalnit eroarea la activarea pluginului.

@rodica-andronache  @ineagu

**Comment by ineagu** [comment]
problema asta e atunci cand faci tranfer pe ftp si ai encoding diferit.
