### ISSUE TITLE
People can post as many comments reviews as they want

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#62]
Source: Forum

A registered user can give a lot of reviews for the same product .
But that falsified the vote . A registered user to give only one vote for a product .
Now he can give a rating in every comments, did is wrong ,
He always write comments , but the ratings only one per product presentation .

@selu91 @ineagu

**Comment by ineagu** [comment]
There should be plugins which allows users to limit comments at 1 per user.

**Comment by UVLabs** [comment]
+1
