### ISSUE TITLE
Add 100% rating influence

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/wp-product-review#66]
in \wp-product-review\admin\inc\config.php, change line 115
`"options"=>array("0"=>"No influence","10"=>"10%","20"=>"20%","30"=>"30%","40"=>"40%","50"=>"50%","60"=>"60%","70"=>"70%","80"=>"80%","90"=>"90%"),`

to

`"options"=>array("0"=>"No influence","10"=>"10%","20"=>"20%","30"=>"30%","40"=>"40%","50"=>"50%","60"=>"60%","70"=>"70%","80"=>"80%","90"=>"90%", "100"=>"100%"),`

This feature was requested many times.

@ineagu @selu91

**Comment by mariusghitulescu** [comment]
and 1 typo in \wp-product-review-pro\inc\addons\WPPR-comparison-table\view\settings_page.php
`<p>Your visitators will be able to sort the products by name or review score.</p>`

*visitors

**Comment by selu91** [comment]
s-a rezolvat in 2.6.3
