### ISSUE TITLE
longer text doesn't look so good

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/wp-product-review#68]
If my text at the "pros" or "cons" are a little bit longer (2 lines), it looks not so good because the indent is missing.
https://wordpress.org/support/topic/two-things-to-improve-1?replies=1#post-7240737

**Comment by selu91** [comment]
@alexandrastann nu am putut sa replica bugul, tu l-ai vazut undeva sau e pe baza celor spuse de el ?
