### ISSUE TITLE
import google fonts issue

### ISSUE THREAD

**Issue by claudiuvertistudio** [Codeinwp/wp-product-review#69]
@selu91 cand instalez pluginul WP product review pe Parallax One unele texte se fac bold-uite si font-urile par altele. M-am uitat prin plugin si in fisierul frontpage.css daca sterg @ import url(...) totul revine la normal.

Asa se vede acum https://drive.google.com/a/vertistudio.com/file/d/0B-5bubkEZeL-aVQtVnM4MlllRXM/view?usp=drivesdk

si asa trebuie sa se vada https://drive.google.com/a/vertistudio.com/file/d/0B-5bubkEZeL-ZVo3N3pBS0tsRnM/view?usp=drivesdk

**Comment by selu91** [comment]
s-a rezolvat in 2.6.3
