### ISSUE TITLE
Rich Snippets on 0% visitor influence

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/wp-product-review#73]
When 'Visitor Review Influence' is turned off, the microtags still show "aggregateRating", instead of "reviewRating".

For author reviews only, microtags should be "reviewRating", this is why rich snippets are not displayed on websites who have only 1 review, the author's.

When Visitor influence is turned off, the microtag should be "reviewRating"

**Comment by selu91** [comment]
Fixed in 2.6.6
