### ISSUE TITLE
Indicator not responsive

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-product-review#86]
@selu91 We have an issue with the comment indicator on the mobile version.

<img width="345" alt="skitch" src="https://cloud.githubusercontent.com/assets/6906834/12942872/00e8d0b0-cfde-11e5-9ece-3d32f85628f3.png">

You can not move the blue point on mobile. I think there is a jQuery issue.

**Comment by ineagu** [comment]
@mileamadalin you opened this issue 1 month before and I closed it, indeed I didn't gave much information, however check closed issues as well 💃
