### ISSUE TITLE
WPPR price parsing issue

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-product-review#89]
@contactashish13 As you can see here : https://wordpress.org/support/topic/new-version-277-problem-with-prices-display?replies=10, when I have added some parsing on the price field, in order to build the rich snippet, I have broken some configs, so we need to do 2 things : 

1) We can do a do_shortcode() before parsing if users used a shortcode there ? Which should fix masterez issue

2) We should add a filter which people can use it super easily to deactivate price parsing + rich snippets ( which @iSaumya can use to fix his issue .

Btw is ok if I create those tasks directly on git when is the case ?

**Comment by contactashish13** [comment]
1) added do_shortcode
2) added support for filter wppr_price_format

**Comment by ineagu** [comment]
I think you misunderstood  the filter thing, I will commit a solution

On Fri, Feb 19, 2016 at 2:15 PM, contactashish13 <notifications@github.com>
wrote:

> 1) added do_shortcode
> 2) added support for filter wppr_price_format
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/89#issuecomment-186208817>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by isaumya** [comment]
looking forward to a fix of this wired issue.

**Comment by ineagu** [comment]
hey, the solution is here :
http://docs.themeisle.com/article/216-price-in-wp-product-review-is-messed-up
if you are using the development version. A public update should come next
week

On Sun, Feb 21, 2016 at 11:45 AM, Saumya Majumder <notifications@github.com>
wrote:

> looking forward to a fix of this wired issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/89#issuecomment-186796142>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by isaumya** [comment]
@ineagu Quick question. Do you guys support only one price value in the latest update? Like $100 but not like $100 - $200 (without using the patch)

**Comment by ineagu** [comment]
Exactly. We did that in order to parse it and add the schema.org Offers markup and show the price in google. Probably the parser part can be improved to support what you have, but is not a priority at the moment.

**Comment by isaumya** [comment]
Yah! I do understand that. Actually when you are reviewing something which has variable pricing but you mention only the starting price of the product, it seems silly to the readers. Like for example if you are reviewing a phone it can have different price depending upon the size variant.

Looking forward to the fix the the public update next week also parsing variable pricing in the future update (may be in next few months).

Actually I'm not using the development version of your plugin I run only the stable version. So, after you push the stable update next week, do I have to add the following in my `functions.php` too?

````
function wppr_test_filter() {
	return false;
}

add_filter('wppr_disable_price_richsnippet','wppr_test_filter');
````

**Comment by ineagu** [comment]
it makes sense, feel free to create an issue and we will work on it later
on.

About 2nd question, you are right, once you update to the new version, just
add that code in functions.php. That will deactivate the parsing and show
what you have in the price field.

On Sun, Feb 21, 2016 at 2:08 PM, Saumya Majumder <notifications@github.com>
wrote:

> Yah! I do understand that. Actually when you are reviewing something which
> has variable pricing but you mention only the starting price of the
> product, it seems silly to the readers. Like for example if you are
> reviewing a phone it can have different price depending upon the size
> variant.
>
> Looking forward to the fix the the public update next week also parsing
> variable pricing in the future update (may be in next few months).
>
> Actually I'm not using the development version of your plugin I run only
> the stable version. So, after you push the stable update next week, do I
> have to add the following in my functions.php too?
>
> function wppr_test_filter() {
>     return false;
> }
>
> add_filter('wppr_disable_price_richsnippet','wppr_test_filter');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/89#issuecomment-186820219>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by isaumya** [comment]
still showing the same problem - https://www.isaumya.com/windows-10-review-is-it-worth-upgrading/

on the latest version of your plugin plus added the following in my theme's function.php file

![Proof](https://cloud.githubusercontent.com/assets/2124755/13303928/fd79597c-db77-11e5-94f9-a0c8bc32b53e.jpg)


```
function wppr_test_filter() {
	return false;
}
add_filter('wppr_disable_price_richsnippet','wppr_test_filter');
```

What to do?

**Comment by ineagu** [comment]
ah sorry, this should return true :)

function wppr_test_filter() {
    return true;
}


On Wed, Feb 24, 2016 at 11:57 PM, Saumya Majumder <notifications@github.com>
wrote:

> still showing the same problem -
> https://www.isaumya.com/windows-10-review-is-it-worth-upgrading/
>
> on the latest version of your plugin plus added the following in my
> theme's function.php file
>
> [image: Proof]
> <https://cloud.githubusercontent.com/assets/2124755/13303928/fd79597c-db77-11e5-94f9-a0c8bc32b53e.jpg>
>
> function wppr_test_filter() {
>     return false;
> }
> add_filter('wppr_disable_price_richsnippet','wppr_test_filter');
>
> What to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/89#issuecomment-188498029>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by isaumya** [comment]
@ineagu sorry but even after making it true, it is still not showing the price properly. You can check the live link yourself.

Current code:

```
function wppr_test_filter() {
	return true;
}
add_filter('wppr_disable_price_richsnippet','wppr_test_filter');
```

**Comment by ineagu** [comment]
added same code on my localhost and worked, not sure what are you doing
wrong, maybe other theme functions.php or don't know..

On Thu, Feb 25, 2016 at 12:03 AM, Saumya Majumder <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> sorry but even after making it true,
> it is still not showing the price properly. You can check the live link
> yourself.
>
> Current code:
>
> function wppr_test_filter() {
>     return true;
> }
> add_filter('wppr_disable_price_richsnippet','wppr_test_filter');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/wp-product-review/issues/89#issuecomment-188501444>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
