### ISSUE TITLE
Limit Top Reviews Widget by Timeframe

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#93]
A user suggested that we limit top review widget by time frame, so a user can select a /week/month/year as an option and show the results based on the reviews posted in that timeframe.

**Comment by HardeepAsrani** [comment]
@selul Another person asked for it.

**Comment by HardeepAsrani** [comment]
+1: A user asked on HS to give this priority. @selul

**Comment by Naismith75** [comment]
Please add this feature, the widget is not useful in the actual way.
