### ISSUE TITLE
Can't disable the review

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-product-review#94]
I tested with everything latest. Once the review is set on, you can't turn it off. No console errors. @selu91

**Comment by selu91** [comment]
@contactashish13 can you check ?

**Comment by contactashish13** [comment]
@selu91 I'm not sure what I should check. Can you please clarify?

**Comment by selu91** [comment]
@HardeepAsrani  can you please help ?

**Comment by HardeepAsrani** [comment]
@contactashish13 Once you turn a post into review from the meta box located in post editor, you can't turn it off. :)

**Comment by selu91** [comment]
@HardeepAsrani it's fixed and live. you can let the users know

**Comment by selu91** [comment]
@HardeepAsrani please close the issue when you acknowledge this

**Comment by HardeepAsrani** [comment]
Got it. :)
